### ISSUE TITLE
real worl lifted mc models

### ISSUE THREAD

**Issue by DerThorsten** [bjoern-andres/graph#24]
are there some real work hdf5 lifted multicut models available.
Would be great to test new solvers on non synthetic models!

Greetings

**Comment by bjoern-andres** [comment]
https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/image-and-video-segmentation/efficient-decomposition-of-image-and-mesh-graphs-by-lifted-multicuts/
